
version: '2'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - redis
    volumes:
      - ".:/go/src/app"
    volumes_from:
      - package
    command: 'go run main.go'
    environment:
      - "GO_ENV=development"
      - "PORT=5000"
    links:
      - db
  redis:
    image: redis:latest
  package:
    image: "busybox"
    volumes:
      - "/go"
  db:
    image: "mongo:latest"
    volumes_from:
      - data
    depends_on:
      - data
  data:
    image: "busybox"
    volumes:
      - "/data/db"
